#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
# 

ignorePatterns:
  - pattern: '^https://platform.openai.com/docs/guides/.*$' # Causes false positives