//
// This source file is part of the Stanford Spezi open source project
//
// SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

import Foundation


/// A structure representing the result of the local LLM.
public struct LLMLocalGenerationResult: Codable {
    /// The input tokens provided to the model.
    public let inputTokens: [Int]
    /// The output tokens generated by the model.
    public let outputTokens: [Int]
    /// The final output text generated by the model.
    public let output: String
    /// The time taken to process the prompt, in seconds. (Time to first token)
    public let promptTime: TimeInterval
    /// The time taken to generate the output, in seconds.
    public let generateTime: TimeInterval
    /// The number of input tokens processed per second during the prompt phase.
    public var promptTokensPerSecond: Double {
        Double(inputTokens.count) / promptTime
    }
    /// The number of output tokens generated per second during the generation phase.
    public var tokensPerSecond: Double {
        Double(outputTokens.count) / generateTime
    }
}
