FROM alpine:latest

LABEL maintainer="Philipp Zagar <zagar@stanford.edu>" \
    org.label-schema.schema-version="1.0" \
    org.label-schema.name="philippzagar/avahi" \
    org.label-schema.description="Simple Avahi docker image" \
    org.label-schema.version="0.1" \
    org.label-schema.url="https://hub.docker.com/r/philippzagar/avahi" \
    org.label-schema.vcs-url="https://github.com/StanfordSpezi/SpeziLLM"

# Install Avahi daemon
RUN apk --no-cache --no-progress add avahi avahi-tools dbus

# Setup services
RUN rm -rf /etc/avahi/services
COPY services/ /etc/avahi/services

# Run Avahi daemon with non-root user, avoid daemonizing to keep container running
COPY docker-entrypoint-sidecar.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Create the D-Bus system bus socket directory
RUN mkdir -p /var/run/dbus && \
    chown messagebus:messagebus /var/run/dbus

ENTRYPOINT ["docker-entrypoint.sh"]