#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

services:
  # Advertises dummy mDNS service to sidecar container
  avahi:
    build:
      context: avahi
    hostname: spezillmfog.local
    networks:
      - avahi

  # Receives advertised dummy mDNS service from avahi container
  avahi-sidecar:
    build:
      context: avahi
      dockerfile: Dockerfile-Sidecar
    hostname: spezillmfog-sidecar.local
    networks:
      - avahi

# Enables to bridge mDNS advertise packages between the two avahi containers
networks:
  avahi:
    driver: bridge